language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - develop

os:
  - linux

cache:
  directories:
  - $HOME/.m2

after_sucess:
- "./ci/before_deploy.sh"
- "./ci/deploy.sh"

notifications:
  email: laaws-dev@lists.lockss.org